version = 1

[[annotations]]
path = ["README.md", ".env"]
precedence = "closest"
SPDX-FileCopyrightText = "Â© 2021 Clifford Weinmann <https://www.cliffordweinmann.com/>"
SPDX-License-Identifier = "Unlicense"
